In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# 1. Carregamento inicial de dados

import pandas as pd
import numpy as np

ANO_MINIMO = 2015

paths = {
    'ind_10_19': '/content/drive/MyDrive/API-6/indicadores-continuidade-coletivos-2010-2019.csv',
    'ind_20_29': '/content/drive/MyDrive/API-6/indicadores-continuidade-coletivos-2020-2029.csv',
    'atributos': '/content/drive/MyDrive/API-6/indicadores-continuidade-coletivos-atributos.csv',
    'limites':   '/content/drive/MyDrive/API-6/indicadores-continuidade-coletivos-limite.csv'
}

def load_csv(path):
    try:
        return pd.read_csv(path, encoding='latin1', sep=';', low_memory=False)
    except Exception as e:
        print(f'Erro ao carregar {path}: {e}')
        return pd.DataFrame()

df_10_19 = load_csv(paths['ind_10_19'])
df_20_29 = load_csv(paths['ind_20_29'])
df_atrib = load_csv(paths['atributos'])
df_limit = load_csv(paths['limites'])

print('Arquivos carregados com sucesso.')
print(f'df_10_19: {df_10_19.shape}')
print(f'df_20_29: {df_20_29.shape}')

Arquivos carregados com sucesso.
df_10_19: (8554625, 9)
df_20_29: (4786829, 9)

In [3]:
# 2. Limpeza e consolidação dos indicadores

def clean_df(df, val_col, date_col='DatGeracaoConjuntoDados'):
    if df.empty:
        return df
    df = df.copy()
    if date_col in df.columns:
        df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
    if val_col in df.columns:
        df[val_col] = df[val_col].astype(str).str.replace(',', '.', regex=False)
        df[val_col] = pd.to_numeric(df[val_col], errors='coerce')
    cols_fix = ['NumCNPJ', 'IdeConjUndConsumidoras', 'AnoIndice', 'NumPeriodoIndice', 'AnoLimiteQualidade']
    for col in cols_fix:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    if 'SigAgente' in df.columns:
        df['SigAgente'] = df['SigAgente'].astype(str).str.strip().str.upper()
    return df

df_10_19 = clean_df(df_10_19, 'VlrIndiceEnviado')
df_20_29 = clean_df(df_20_29, 'VlrIndiceEnviado')
df_atrib = clean_df(df_atrib, 'VlrIndiceEnviado')

df_10_29 = pd.concat([df_10_19, df_20_29], ignore_index=True)

df_limit_raw = load_csv(paths['limites'])
df_limit_processed = clean_df(df_limit_raw.copy(), 'VlrLimite')

if 'AnoIndice' in df_10_29.columns:
    df_10_29 = df_10_29[df_10_29['AnoIndice'] >= ANO_MINIMO].copy()
if 'AnoIndice' in df_atrib.columns:
    df_atrib = df_atrib[df_atrib['AnoIndice'] >= ANO_MINIMO].copy()
if 'AnoLimiteQualidade' in df_limit_processed.columns:
    df_limit_processed = df_limit_processed[df_limit_processed['AnoLimiteQualidade'] >= ANO_MINIMO].copy()

df_limit_processed = df_limit_processed.rename(
    columns={'AnoLimiteQualidade': 'AnoIndice', 'VlrLimite': 'VlrIndiceEnviado'}
)
df_limit_processed['TipoRegistro'] = 'Limite'

df_limit_dec = df_limit_processed.copy(); df_limit_dec['SigIndicador'] = 'DEC'
df_limit_fec = df_limit_processed.copy(); df_limit_fec['SigIndicador'] = 'FEC'
df_limit = pd.concat([df_limit_dec, df_limit_fec], ignore_index=True)

df_apurados = pd.concat([df_10_29, df_atrib], ignore_index=True)
df_apurados['TipoRegistro'] = 'Apurado'

common_cols = [
    'IdeConjUndConsumidoras', 'SigIndicador', 'AnoIndice', 'NumPeriodoIndice',
    'VlrIndiceEnviado', 'TipoRegistro'
]

df_indicadores = pd.concat([
    df_apurados[[c for c in common_cols if c in df_apurados.columns]],
    df_limit[[c for c in common_cols if c in df_limit.columns]]
], ignore_index=True)

df_indicadores['IdeConjUndConsumidoras'] = df_indicadores['IdeConjUndConsumidoras'].astype(int)
df_indicadores['AnoIndice'] = df_indicadores['AnoIndice'].astype(int)
df_indicadores['NumPeriodoIndice_key'] = pd.to_numeric(
    df_indicadores['NumPeriodoIndice'], errors='coerce'
).fillna(0).astype(int)

In [ ]:
# 3. Instalação do Prophet
# Prophet é muito mais leve que redes neurais: sem GPU, sem batches,
# fit em segundos por série — ideal para 6000+ unidades.

!pip install prophet -q

In [ ]:
# 4. Imports para Prophet

import os
import gc
import logging
import warnings
from prophet import Prophet

warnings.filterwarnings('ignore')
# Silencia logs verbosos do Prophet/Stan
logging.getLogger('prophet').setLevel(logging.ERROR)
logging.getLogger('cmdstanpy').setLevel(logging.ERROR)

## INÍCIO DE TRATAMENTO PARA SÉRIES TEMPORAIS E TREINAMENTO COM PROPHET - DEC

In [ ]:
# 5. Preparação da série DEC

df_dec = df_indicadores[df_indicadores['SigIndicador'] == 'DEC'].copy()
df_dec = df_dec.dropna(subset=['NumPeriodoIndice'])
df_dec['data'] = pd.to_datetime(
    df_dec['AnoIndice'].astype(int).astype(str) + '-' +
    df_dec['NumPeriodoIndice_key'].astype(int).astype(str).str.zfill(2) + '-01'
)

data_max = '2026-02-01'
ids_validos = df_dec.loc[df_dec['data'] == data_max, 'IdeConjUndConsumidoras'].unique()

dec_por_agente = (
    df_dec[df_dec['IdeConjUndConsumidoras'].isin(ids_validos)]
    .sort_values(['IdeConjUndConsumidoras', 'data'])
)

print(f'Unidades DEC válidas: {len(ids_validos)}')
dec_por_agente.head()

Unidades DEC válidas: 2740

,IdeConjUndConsumidoras,SigIndicador,AnoIndice,NumPeriodoIndice,VlrIndiceEnviado,TipoRegistro,NumPeriodoIndice_key,data
627874,964,DEC,2015,1.0,0.49,Apurado,1,2015-01-01
636415,964,DEC,2015,2.0,1.17,Apurado,2,2015-02-01
634006,964,DEC,2015,3.0,1.20,Apurado,3,2015-03-01
615391,964,DEC,2015,4.0,0.54,Apurado,4,2015-04-01
607507,964,DEC,2015,5.0,1.25,Apurado,5,2015-05-01

In [ ]:
# 6. Parâmetros e função Prophet para DEC
#
# Configuração mínima e eficiente:
#   - yearly_seasonality=True  → captura padrão anual (DEC/FEC têm forte sazonalidade)
#   - weekly_seasonality=False → dados mensais, não faz sentido
#   - daily_seasonality=False  → idem
#   - n_changepoints=10        → reduzido para evitar overfitting em séries curtas
#   - Sem regressores extras   → mantém velocidade para 6 000+ unidades

HORIZONTE   = 12   # meses a prever
MIN_AMOSTRAS = 24  # mínimo de pontos históricos (2 anos)

def processar_unidade_prophet(cod, df_unit, indicador='DEC'):
    df_unit = (
        df_unit[['data', 'VlrIndiceEnviado']]
        .dropna()
        .rename(columns={'data': 'ds', 'VlrIndiceEnviado': 'y'})
        .reset_index(drop=True)
    )

    if len(df_unit) < MIN_AMOSTRAS:
        return None  # histórico insuficiente

    # Treina com todos os dados disponíveis
    m = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=False,
        daily_seasonality=False,
        n_changepoints=10,
        seasonality_mode='additive',
    )
    m.fit(df_unit)

    # Calcula MAE no último HORIZONTE meses (validação interna)
    if len(df_unit) >= HORIZONTE + MIN_AMOSTRAS:
        df_train_val = df_unit.iloc[:-HORIZONTE]
        df_test_val  = df_unit.iloc[-HORIZONTE:]
        m_val = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=False,
            daily_seasonality=False,
            n_changepoints=10,
            seasonality_mode='additive',
        )
        m_val.fit(df_train_val)
        future_val = m_val.make_future_dataframe(periods=HORIZONTE, freq='MS', include_history=False)
        forecast_val = m_val.predict(future_val)
        mae_val = float(np.mean(np.abs(forecast_val['yhat'].values - df_test_val['y'].values)))
    else:
        mae_val = float('nan')

    # Previsão futura com o modelo completo
    future = m.make_future_dataframe(periods=HORIZONTE, freq='MS', include_history=False)
    forecast = m.predict(future)

    df_prev = pd.DataFrame({
        'cod_unidade': cod,
        'indicador': indicador,
        'mae': round(mae_val, 6),
        'data': forecast['ds'],
        'previsao': forecast['yhat'].round(6),
        'previsao_lower': forecast['yhat_lower'].round(6),
        'previsao_upper': forecast['yhat_upper'].round(6),
    })

    return {'cod_unidade': cod, 'mae': mae_val, 'previsoes': df_prev}

In [ ]:
# 7. Treinamento Prophet para todas as unidades - DEC
#
# Salva parcialmente a cada CHECKPOINT unidades para não perder
# progresso em caso de queda do runtime (muito comum com 6 000+ treinos).

CAMINHO_PREVISOES_DEC = '/content/drive/MyDrive/API-6/previsoes_dec_prophet_todas_unidades.csv'
CHECKPOINT = 500  # salva CSV parcial a cada N unidades

todas_unidades_dec   = dec_por_agente['IdeConjUndConsumidoras'].unique()
resultados_dec       = []
todas_previsoes_dec  = []

for i, cod in enumerate(todas_unidades_dec, start=1):
    df_unit = dec_por_agente[dec_por_agente['IdeConjUndConsumidoras'] == cod].copy()
    try:
        res = processar_unidade_prophet(cod, df_unit, indicador='DEC')
        if res:
            resultados_dec.append({'cod_unidade': res['cod_unidade'], 'mae': res['mae']})
            todas_previsoes_dec.append(res['previsoes'])
            print(f"✓ [{i}/{len(todas_unidades_dec)}] Unidade {cod} | MAE: {res['mae']:.4f}")
        else:
            print(f"⚠ [{i}/{len(todas_unidades_dec)}] Unidade {cod} | ignorada (dados insuficientes)")
    except Exception as e:
        print(f"✗ [{i}/{len(todas_unidades_dec)}] Unidade {cod} | erro: {e}")
    finally:
        gc.collect()

    # Checkpoint: salva CSV parcial periodicamente
    if i % CHECKPOINT == 0 and todas_previsoes_dec:
        pd.concat(todas_previsoes_dec, ignore_index=True).assign(
            data=lambda d: d['data'].dt.strftime('%Y-%m-%d')
        ).to_csv(CAMINHO_PREVISOES_DEC, sep=';', decimal=',', index=False)
        print(f"  → Checkpoint salvo ({i} unidades processadas)")

✓ [1/2740] Unidade 964 | MAE: 0.2643
✓ [2/2740] Unidade 2142 | MAE: 0.1766
✓ [3/2740] Unidade 2922 | MAE: 0.1279
✓ [4/2740] Unidade 5273 | MAE: 0.2447
✓ [5/2740] Unidade 12474 | MAE: 0.3276
✓ [6/2740] Unidade 12475 | MAE: 1.0682
✓ [7/2740] Unidade 12476 | MAE: 0.0864
✓ [8/2740] Unidade 12477 | MAE: 0.6200
✓ [9/2740] Unidade 12478 | MAE: 0.7503
✓ [10/2740] Unidade 12479 | MAE: 0.2749
✓ [11/2740] Unidade 12481 | MAE: 0.8753
✓ [12/2740] Unidade 12482 | MAE: 0.2086
✓ [13/2740] Unidade 12483 | MAE: 0.4704
✓ [14/2740] Unidade 12484 | MAE: 0.6533
✓ [15/2740] Unidade 12485 | MAE: 0.5246
✓ [16/2740] Unidade 12486 | MAE: 2.0182
✓ [17/2740] Unidade 12487 | MAE: 1.0992
✓ [18/2740] Unidade 12488 | MAE: 0.9380
✓ [19/2740] Unidade 12489 | MAE: 1.8931
✓ [20/2740] Unidade 12524 | MAE: 2.1562
✓ [21/2740] Unidade 12525 | MAE: 1.6937
✓ [22/2740] Unidade 12532 | MAE: 1.1469
✓ [23/2740] Unidade 12539 | MAE: 1.1747
✓ [24/2740] Unidade 12540 | MAE: 0.5533
✓ [25/2740] Unidade 12541 | MAE: 2.3173
✓ [26/2740] Unidade 12542 | MAE: 0.5962
✓ [27/2740] Unidade 12543 | MAE: 1.7721
✓ [28/2740] Unidade 12546 | MAE: 2.1562
✓ [29/2740] Unidade 12547 | MAE: 1.3350
✓ [30/2740] Unidade 12553 | MAE: 0.7092
✓ [31/2740] Unidade 12559 | MAE: 0.2017
✓ [32/2740] Unidade 12570 | MAE: 0.7874
✓ [33/2740] Unidade 12571 | MAE: 1.6534
✓ [34/2740] Unidade 12574 | MAE: 0.6205
✓ [35/2740] Unidade 12575 | MAE: 0.4924
✓ [36/2740] Unidade 12576 | MAE: 7.2439
✓ [37/2740] Unidade 12582 | MAE: 1.8044
✓ [38/2740] Unidade 12584 | MAE: 2.8734
✓ [39/2740] Unidade 12586 | MAE: 0.5630
✓ [40/2740] Unidade 12589 | MAE: 0.5532
✓ [41/2740] Unidade 12591 | MAE: 1.5592
✓ [42/2740] Unidade 12592 | MAE: 1.1999
✓ [43/2740] Unidade 12593 | MAE: 1.2068
✓ [44/2740] Unidade 12594 | MAE: 2.3479
✓ [45/2740] Unidade 12595 | MAE: 1.5890
✓ [46/2740] Unidade 12598 | MAE: 1.6166
✓ [47/2740] Unidade 12599 | MAE: 2.0393
✓ [48/2740] Unidade 12600 | MAE: 0.9822
✓ [49/2740] Unidade 12634 | MAE: 0.3422
✓ [50/2740] Unidade 12635 | MAE: 0.8028
✓ [51/2740] Unidade 12636 | MAE: 0.4899
✓ [52/2740] Unidade 12638 | MAE: 0.7261
✓ [53/2740] Unidade 12639 | MAE: 0.1096
✓ [54/2740] Unidade 12640 | MAE: 0.2852
✓ [55/2740] Unidade 12644 | MAE: 0.3765
✓ [56/2740] Unidade 12648 | MAE: 1.1636
✓ [57/2740] Unidade 12649 | MAE: 0.6854
✓ [58/2740] Unidade 12652 | MAE: 0.7605
✓ [59/2740] Unidade 12654 | MAE: 0.5526
✓ [60/2740] Unidade 12656 | MAE: 0.5210
✓ [61/2740] Unidade 12657 | MAE: 0.1947
✓ [62/2740] Unidade 12658 | MAE: 2.6348
✓ [63/2740] Unidade 12664 | MAE: 0.6236
✓ [64/2740] Unidade 12668 | MAE: 0.2305
✓ [65/2740] Unidade 12671 | MAE: 0.3227
✓ [66/2740] Unidade 12673 | MAE: 0.8444
✓ [67/2740] Unidade 12674 | MAE: 0.2199
✓ [68/2740] Unidade 12680 | MAE: 0.2421
✓ [69/2740] Unidade 12681 | MAE: 0.1363
✓ [70/2740] Unidade 12683 | MAE: 0.5719
✓ [71/2740] Unidade 12686 | MAE: 1.0954
✓ [72/2740] Unidade 12687 | MAE: 1.2317
✓ [73/2740] Unidade 12688 | MAE: 0.6181
✓ [74/2740] Unidade 12689 | MAE: 2.1590
✓ [75/2740] Unidade 12690 | MAE: 0.8551
✓ [76/2740] Unidade 12691 | MAE: 1.3490
✓ [77/2740] Unidade 12696 | MAE: 1.5974
✓ [78/2740] Unidade 12703 | MAE: 1.5758
✓ [79/2740] Unidade 12706 | MAE: 0.7781
✓ [80/2740] Unidade 12707 | MAE: 1.1790
✓ [81/2740] Unidade 12708 | MAE: 0.4028
✓ [82/2740] Unidade 12709 | MAE: 1.0508
✓ [83/2740] Unidade 12711 | MAE: 0.6890
✓ [84/2740] Unidade 12713 | MAE: 0.9396
✓ [85/2740] Unidade 12715 | MAE: 0.9685
✓ [86/2740] Unidade 12716 | MAE: 0.6444
✓ [87/2740] Unidade 12718 | MAE: 0.3628
✓ [88/2740] Unidade 12720 | MAE: 1.3219
✓ [89/2740] Unidade 12721 | MAE: 0.4876
✓ [90/2740] Unidade 12722 | MAE: 0.2304
✓ [91/2740] Unidade 12723 | MAE: 0.1471
✓ [92/2740] Unidade 12730 | MAE: 0.5933
✓ [93/2740] Unidade 12743 | MAE: 0.4288
✓ [94/2740] Unidade 12785 | MAE: 0.4466
✓ [95/2740] Unidade 12786 | MAE: 0.4703
✓ [96/2740] Unidade 12788 | MAE: 0.2317
✓ [97/2740] Unidade 12791 | MAE: 0.2719
✓ [98/2740] Unidade 12798 | MAE: 0.3168
✓ [99/2740] Unidade 12800 | MAE: 0.2748
✓ [100/2740] Unidade 12803 | MAE: 3.5632
✓ [101/2740] Unidade 12805 | MAE: 0.2474
✓ [102/2740] Unidade 12807 | MAE: 0.8546
✓ [103/2740] Unidade 12819 | MAE: 0.2294
✓ [104/2740] Unidade 12825 | MAE: 0.4504
✓ [105/2740] Unidade 12827 | MAE: 0.5449
✓ [106/2740] Unidade 12829 | MAE: 0.3135
✓ [107/2740] Unidade 12831 | MAE: 1.8179
✓ [108/2740] Unidade 12832 | MAE: 0.3245
✓ [109/2740] Unidade 12834 | MAE: 0.7535
✓ [110/2740] Unidade 12836 | MAE: 0.3302
✓ [111/2740] Unidade 12840 | MAE: 0.6166
✓ [112/2740] Unidade 12847 | MAE: 0.6193
✓ [113/2740] Unidade 12849 | MAE: 0.2437
✓ [114/2740] Unidade 12850 | MAE: 0.7350
✓ [115/2740] Unidade 12852 | MAE: 0.2818
✓ [116/2740] Unidade 12854 | MAE: 0.8910
✓ [117/2740] Unidade 12856 | MAE: 0.3796
✓ [118/2740] Unidade 12860 | MAE: 0.3427
✓ [119/2740] Unidade 12863 | MAE: 2.2663
✓ [120/2740] Unidade 12865 | MAE: 0.5594
✓ [121/2740] Unidade 12867 | MAE: 1.8396
✓ [122/2740] Unidade 12869 | MAE: 0.3114
✓ [123/2740] Unidade 12871 | MAE: 1.4722
✓ [124/2740] Unidade 12873 | MAE: 0.2813
✓ [125/2740] Unidade 12875 | MAE: 1.1312
✓ [126/2740] Unidade 12878 | MAE: 0.3515
✓ [127/2740] Unidade 12879 | MAE: 0.1519
✓ [128/2740] Unidade 12881 | MAE: 0.5254
✓ [129/2740] Unidade 12884 | MAE: 0.4650
✓ [130/2740] Unidade 12886 | MAE: 0.7856
✓ [131/2740] Unidade 12888 | MAE: 0.3116
✓ [132/2740] Unidade 12889 | MAE: 1.1934
✓ [133/2740] Unidade 12891 | MAE: 0.5657
✓ [134/2740] Unidade 12894 | MAE: 0.1825
✓ [135/2740] Unidade 12898 | MAE: 0.3856
✓ [136/2740] Unidade 12901 | MAE: 0.6438
✓ [137/2740] Unidade 12903 | MAE: 0.6038
✓ [138/2740] Unidade 12905 | MAE: 0.7715
✓ [139/2740] Unidade 13015 | MAE: 0.2089
✓ [140/2740] Unidade 13016 | MAE: 0.4181
✓ [141/2740] Unidade 13017 | MAE: 0.4151
✓ [142/2740] Unidade 13019 | MAE: 0.3567
✓ [143/2740] Unidade 13021 | MAE: 0.3347
✓ [144/2740] Unidade 13022 | MAE: 0.4879
✓ [145/2740] Unidade 13024 | MAE: 1.2776
✓ [146/2740] Unidade 13025 | MAE: 0.3397
✓ [147/2740] Unidade 13027 | MAE: 0.3030
✓ [148/2740] Unidade 13028 | MAE: 0.3454
✓ [149/2740] Unidade 13031 | MAE: 0.2364
✓ [150/2740] Unidade 13032 | MAE: 0.3672
✓ [151/2740] Unidade 13033 | MAE: 0.3262
✓ [152/2740] Unidade 13034 | MAE: 0.1218
✓ [153/2740] Unidade 13035 | MAE: 0.3697
✓ [154/2740] Unidade 13037 | MAE: 0.1568
✓ [155/2740] Unidade 13038 | MAE: 0.3200
✓ [156/2740] Unidade 13040 | MAE: 0.1963
✓ [157/2740] Unidade 13041 | MAE: 0.2944
✓ [158/2740] Unidade 13042 | MAE: 0.0996
✓ [159/2740] Unidade 13043 | MAE: 0.2987
✓ [160/2740] Unidade 13044 | MAE: 0.2913
✓ [161/2740] Unidade 13045 | MAE: 0.1461
✓ [162/2740] Unidade 13046 | MAE: 0.2692
✓ [163/2740] Unidade 13047 | MAE: 0.7700
✓ [164/2740] Unidade 13048 | MAE: 0.5693
✓ [165/2740] Unidade 13049 | MAE: 0.3313
✓ [166/2740] Unidade 13050 | MAE: 0.2655
✓ [167/2740] Unidade 13051 | MAE: 1.6325
✓ [168/2740] Unidade 13052 | MAE: 0.2495
✓ [169/2740] Unidade 13053 | MAE: 0.5414
✓ [170/2740] Unidade 13055 | MAE: 0.7759
✓ [171/2740] Unidade 13056 | MAE: 0.2037
✓ [172/2740] Unidade 13057 | MAE: 0.8213
✓ [173/2740] Unidade 13058 | MAE: 0.5536
✓ [174/2740] Unidade 13060 | MAE: 1.0516
✓ [175/2740] Unidade 13061 | MAE: 0.2770
✓ [176/2740] Unidade 13064 | MAE: 0.2276
✓ [177/2740] Unidade 13066 | MAE: 0.4933
✓ [178/2740] Unidade 13067 | MAE: 0.6941
✓ [179/2740] Unidade 13068 | MAE: 0.2032
✓ [180/2740] Unidade 13069 | MAE: 0.7336
✓ [181/2740] Unidade 13070 | MAE: 0.3383
✓ [182/2740] Unidade 13071 | MAE: 0.4611
✓ [183/2740] Unidade 13074 | MAE: 0.3204
✓ [184/2740] Unidade 13075 | MAE: 0.4619
✓ [185/2740] Unidade 13076 | MAE: 0.3106
✓ [186/2740] Unidade 13078 | MAE: 0.9294
✓ [187/2740] Unidade 13079 | MAE: 0.2537
✓ [188/2740] Unidade 13080 | MAE: 0.2705
✓ [189/2740] Unidade 13082 | MAE: 0.1689
✓ [190/2740] Unidade 13084 | MAE: 0.7599
✓ [191/2740] Unidade 13086 | MAE: 0.2647
✓ [192/2740] Unidade 13087 | MAE: 0.7453
✓ [193/2740] Unidade 13088 | MAE: 0.8821
✓ [194/2740] Unidade 13089 | MAE: 0.3340
✓ [195/2740] Unidade 13090 | MAE: 0.8196
✓ [196/2740] Unidade 13091 | MAE: 0.1298
✓ [197/2740] Unidade 13092 | MAE: 0.3923
✓ [198/2740] Unidade 13093 | MAE: 0.2818
✓ [199/2740] Unidade 13094 | MAE: 0.5281
✓ [200/2740] Unidade 13098 | MAE: 0.2141
✓ [201/2740] Unidade 13103 | MAE: 1.1781
✓ [202/2740] Unidade 13104 | MAE: 0.9076
✓ [203/2740] Unidade 13107 | MAE: 0.5588
✓ [204/2740] Unidade 13108 | MAE: 1.0892
✓ [205/2740] Unidade 13109 | MAE: 0.3526
✓ [206/2740] Unidade 13111 | MAE: 2.2288
✓ [207/2740] Unidade 13112 | MAE: 1.4183
✓ [208/2740] Unidade 13114 | MAE: 1.3073
✓ [209/2740] Unidade 13115 | MAE: 1.8489
✓ [210/2740] Unidade 13116 | MAE: 0.5115
✓ [211/2740] Unidade 13118 | MAE: 0.8386
✓ [212/2740] Unidade 13119 | MAE: 1.1940
✓ [213/2740] Unidade 13122 | MAE: 1.4015
✓ [214/2740] Unidade 13123 | MAE: 0.8562
✓ [215/2740] Unidade 13124 | MAE: 0.5513
✓ [216/2740] Unidade 13129 | MAE: 0.7153
✓ [217/2740] Unidade 13133 | MAE: 0.8976
✓ [218/2740] Unidade 13136 | MAE: 0.8869
✓ [219/2740] Unidade 13137 | MAE: 1.0813
✓ [220/2740] Unidade 13138 | MAE: 0.8323
✓ [221/2740] Unidade 13155 | MAE: 0.2094
✓ [222/2740] Unidade 13166 | MAE: 0.0945
✓ [223/2740] Unidade 13178 | MAE: 0.1130
✓ [224/2740] Unidade 13183 | MAE: 0.7106
✓ [225/2740] Unidade 13185 | MAE: 0.3036
✓ [226/2740] Unidade 13186 | MAE: 0.4195
✓ [227/2740] Unidade 13187 | MAE: 0.2344
✓ [228/2740] Unidade 13188 | MAE: 0.1840
✓ [229/2740] Unidade 13189 | MAE: 0.3437
✓ [230/2740] Unidade 13191 | MAE: 0.2145
✓ [231/2740] Unidade 13192 | MAE: 0.2392
✓ [232/2740] Unidade 13193 | MAE: 0.3022
✓ [233/2740] Unidade 13194 | MAE: 0.4504
✓ [234/2740] Unidade 13201 | MAE: 0.7249
✓ [235/2740] Unidade 13202 | MAE: 0.5976
✓ [236/2740] Unidade 13204 | MAE: 0.5268
✓ [237/2740] Unidade 13205 | MAE: 0.1758
✓ [238/2740] Unidade 13207 | MAE: 0.2129
✓ [239/2740] Unidade 13208 | MAE: 0.2658
✓ [240/2740] Unidade 13209 | MAE: 0.1986
✓ [241/2740] Unidade 13214 | MAE: 0.2817
✓ [242/2740] Unidade 13216 | MAE: 0.4987
✓ [243/2740] Unidade 13218 | MAE: 0.2823
✓ [244/2740] Unidade 13219 | MAE: 0.1550
✓ [245/2740] Unidade 13220 | MAE: 0.1691
✓ [246/2740] Unidade 13226 | MAE: 0.1112
✓ [247/2740] Unidade 13230 | MAE: 0.3954
✓ [248/2740] Unidade 13234 | MAE: 0.8132
✓ [249/2740] Unidade 13235 | MAE: 0.4084
✓ [250/2740] Unidade 13236 | MAE: 0.2231
✓ [251/2740] Unidade 13238 | MAE: 1.3692
✓ [252/2740] Unidade 13239 | MAE: 0.3220
✓ [253/2740] Unidade 13240 | MAE: 0.7030
✓ [254/2740] Unidade 13242 | MAE: 0.5832
✓ [255/2740] Unidade 13244 | MAE: 0.6417
✓ [256/2740] Unidade 13245 | MAE: 1.0354
✓ [257/2740] Unidade 13246 | MAE: 0.5271
✓ [258/2740] Unidade 13247 | MAE: 0.8026
✓ [259/2740] Unidade 13248 | MAE: 0.3400
✓ [260/2740] Unidade 13249 | MAE: 0.1097
✓ [261/2740] Unidade 13250 | MAE: 0.6906
✓ [262/2740] Unidade 13251 | MAE: 0.4269
✓ [263/2740] Unidade 13252 | MAE: 0.6891
✓ [264/2740] Unidade 13253 | MAE: 0.8730
✓ [265/2740] Unidade 13254 | MAE: 0.1903
✓ [266/2740] Unidade 13255 | MAE: 0.1164
✓ [267/2740] Unidade 13256 | MAE: 1.1026
✓ [268/2740] Unidade 13257 | MAE: 0.3254
✓ [269/2740] Unidade 13258 | MAE: 0.3140
✓ [270/2740] Unidade 13260 | MAE: 1.0119
✓ [271/2740] Unidade 13261 | MAE: 0.3646
✓ [272/2740] Unidade 13263 | MAE: 0.3028
✓ [273/2740] Unidade 13264 | MAE: 0.2880
✓ [274/2740] Unidade 13265 | MAE: 0.3578
✓ [275/2740] Unidade 13267 | MAE: 0.4511
✓ [276/2740] Unidade 13270 | MAE: 0.3069
✓ [277/2740] Unidade 13272 | MAE: 0.3125
✓ [278/2740] Unidade 13273 | MAE: 0.3382
✓ [279/2740] Unidade 13274 | MAE: 0.1075
✓ [280/2740] Unidade 13275 | MAE: 1.0117
✓ [281/2740] Unidade 13276 | MAE: 0.1215
✓ [282/2740] Unidade 13279 | MAE: 1.2927
✓ [283/2740] Unidade 13280 | MAE: 0.3538
✓ [284/2740] Unidade 13281 | MAE: 0.2334
✓ [285/2740] Unidade 13282 | MAE: 0.1809
✓ [286/2740] Unidade 13283 | MAE: 0.6260
✓ [287/2740] Unidade 13284 | MAE: 0.2127
✓ [288/2740] Unidade 13285 | MAE: 0.4147
✓ [289/2740] Unidade 13286 | MAE: 0.9443
✓ [290/2740] Unidade 13288 | MAE: 0.7545
✓ [291/2740] Unidade 13289 | MAE: 0.4793
✓ [292/2740] Unidade 13290 | MAE: 0.2641
✓ [293/2740] Unidade 13291 | MAE: 0.4979
✓ [294/2740] Unidade 13292 | MAE: 0.1762
✓ [295/2740] Unidade 13293 | MAE: 0.2811
✓ [296/2740] Unidade 13295 | MAE: 0.1867
✓ [297/2740] Unidade 13296 | MAE: 0.2737
✓ [298/2740] Unidade 13297 | MAE: 0.5044
✓ [299/2740] Unidade 13298 | MAE: 0.3823
✓ [300/2740] Unidade 13299 | MAE: 0.2394
✓ [301/2740] Unidade 13300 | MAE: 0.1714
✓ [302/2740] Unidade 13302 | MAE: 0.5949
✓ [303/2740] Unidade 13304 | MAE: 0.6409
✓ [304/2740] Unidade 13305 | MAE: 0.4081
✓ [305/2740] Unidade 13307 | MAE: 0.3604
✓ [306/2740] Unidade 13308 | MAE: 0.6611
✓ [307/2740] Unidade 13312 | MAE: 0.3754
✓ [308/2740] Unidade 13314 | MAE: 0.6522
✓ [309/2740] Unidade 13315 | MAE: 0.6736
✓ [310/2740] Unidade 13317 | MAE: 0.2057
✓ [311/2740] Unidade 13318 | MAE: 0.3070
✓ [312/2740] Unidade 13319 | MAE: 0.2971
✓ [313/2740] Unidade 13320 | MAE: 0.2003
✓ [314/2740] Unidade 13321 | MAE: 0.3649
✓ [315/2740] Unidade 13322 | MAE: 0.2519
✓ [316/2740] Unidade 13325 | MAE: 0.3054
✓ [317/2740] Unidade 13327 | MAE: 0.6601
✓ [318/2740] Unidade 13328 | MAE: 0.8037
✓ [319/2740] Unidade 13329 | MAE: 0.3511
✓ [320/2740] Unidade 13330 | MAE: 0.4595
✓ [321/2740] Unidade 13331 | MAE: 0.5089
✓ [322/2740] Unidade 13332 | MAE: 0.6363
✓ [323/2740] Unidade 13334 | MAE: 0.1367
✓ [324/2740] Unidade 13336 | MAE: 0.3484
✓ [325/2740] Unidade 13339 | MAE: 0.1483
✓ [326/2740] Unidade 13340 | MAE: 0.5225
✓ [327/2740] Unidade 13342 | MAE: 0.1284
✓ [328/2740] Unidade 13343 | MAE: 0.4817
✓ [329/2740] Unidade 13344 | MAE: 0.2132
✓ [330/2740] Unidade 13345 | MAE: 0.4938
✓ [331/2740] Unidade 13346 | MAE: 0.2314
✓ [332/2740] Unidade 13347 | MAE: 0.3569
✓ [333/2740] Unidade 13348 | MAE: 0.4519
✓ [334/2740] Unidade 13351 | MAE: 0.2041
✓ [335/2740] Unidade 13352 | MAE: 0.2555
✓ [336/2740] Unidade 13353 | MAE: 0.4927
✓ [337/2740] Unidade 13355 | MAE: 0.4613
✓ [338/2740] Unidade 13356 | MAE: 0.2116
✓ [339/2740] Unidade 13357 | MAE: 0.3590
✓ [340/2740] Unidade 13359 | MAE: 0.2620
✓ [341/2740] Unidade 13360 | MAE: 0.1309
✓ [342/2740] Unidade 13363 | MAE: 0.5722
✓ [343/2740] Unidade 13364 | MAE: 0.2548
✓ [344/2740] Unidade 13365 | MAE: 0.1222
✓ [345/2740] Unidade 13367 | MAE: 0.1128
✓ [346/2740] Unidade 13369 | MAE: 0.4922
✓ [347/2740] Unidade 13370 | MAE: 0.3160
✓ [348/2740] Unidade 13372 | MAE: 0.4343
✓ [349/2740] Unidade 13374 | MAE: 0.2895
✓ [350/2740] Unidade 13375 | MAE: 1.0461
✓ [351/2740] Unidade 13376 | MAE: 0.3297
✓ [352/2740] Unidade 13381 | MAE: 0.1883
✓ [353/2740] Unidade 13382 | MAE: 0.5847
✓ [354/2740] Unidade 13384 | MAE: 0.2235
✓ [355/2740] Unidade 13385 | MAE: 0.1105
✓ [356/2740] Unidade 13387 | MAE: 0.6282
✓ [357/2740] Unidade 13388 | MAE: 0.3945
✓ [358/2740] Unidade 13389 | MAE: 0.5274
✓ [359/2740] Unidade 13390 | MAE: 1.6375
✓ [360/2740] Unidade 13391 | MAE: 0.3700
✓ [361/2740] Unidade 13392 | MAE: 0.3843
✓ [362/2740] Unidade 13394 | MAE: 0.8425
✓ [363/2740] Unidade 13395 | MAE: 0.1749
✓ [364/2740] Unidade 13396 | MAE: 0.8307
✓ [365/2740] Unidade 13397 | MAE: 0.1173
✓ [366/2740] Unidade 13398 | MAE: 0.7185
✓ [367/2740] Unidade 13399 | MAE: 0.3454
✓ [368/2740] Unidade 13401 | MAE: 0.1776
✓ [369/2740] Unidade 13402 | MAE: 0.5153
✓ [370/2740] Unidade 13408 | MAE: 0.2644
✓ [371/2740] Unidade 13412 | MAE: 1.2577
✓ [372/2740] Unidade 13413 | MAE: 0.4023
✓ [373/2740] Unidade 13414 | MAE: 0.3413
✓ [374/2740] Unidade 13416 | MAE: 0.2668
✓ [375/2740] Unidade 13417 | MAE: 0.3894
✓ [376/2740] Unidade 13420 | MAE: 0.1673
✓ [377/2740] Unidade 13421 | MAE: 0.3383
✓ [378/2740] Unidade 13423 | MAE: 0.5805
✓ [379/2740] Unidade 13424 | MAE: 0.5517
✓ [380/2740] Unidade 13425 | MAE: 0.5176
✓ [381/2740] Unidade 13426 | MAE: 0.6165
✓ [382/2740] Unidade 13430 | MAE: 0.5678
✓ [383/2740] Unidade 13431 | MAE: 0.4225
✓ [384/2740] Unidade 13432 | MAE: 0.2521
✓ [385/2740] Unidade 13434 | MAE: 0.4862
✓ [386/2740] Unidade 13435 | MAE: 0.2021
✓ [387/2740] Unidade 13438 | MAE: 0.4306
✓ [388/2740] Unidade 13439 | MAE: 0.1169
✓ [389/2740] Unidade 13441 | MAE: 0.6204
✓ [390/2740] Unidade 13443 | MAE: 0.8125
✓ [391/2740] Unidade 13447 | MAE: 0.8841
✓ [392/2740] Unidade 13448 | MAE: 0.6333
✓ [393/2740] Unidade 13449 | MAE: 0.1509
✓ [394/2740] Unidade 13450 | MAE: 0.2427
✓ [395/2740] Unidade 13451 | MAE: 0.2178
✓ [396/2740] Unidade 13452 | MAE: 0.1031
✓ [397/2740] Unidade 13453 | MAE: 0.3687
✓ [398/2740] Unidade 13454 | MAE: 0.2499
✓ [399/2740] Unidade 13455 | MAE: 0.3618
✓ [400/2740] Unidade 13456 | MAE: 0.1343
✓ [401/2740] Unidade 13457 | MAE: 0.1828
✓ [402/2740] Unidade 13458 | MAE: 0.1691
✓ [403/2740] Unidade 13460 | MAE: 0.2106
✓ [404/2740] Unidade 13463 | MAE: 0.4780
✓ [405/2740] Unidade 13465 | MAE: 0.3341
✓ [406/2740] Unidade 13466 | MAE: 0.1863
✓ [407/2740] Unidade 13467 | MAE: 0.1561
✓ [408/2740] Unidade 13468 | MAE: 0.3313
✓ [409/2740] Unidade 13469 | MAE: 0.3074
✓ [410/2740] Unidade 13470 | MAE: 0.3250
✓ [411/2740] Unidade 13471 | MAE: 0.3770
✓ [412/2740] Unidade 13472 | MAE: 0.3332
✓ [413/2740] Unidade 13473 | MAE: 0.2051
✓ [414/2740] Unidade 13474 | MAE: 0.1730
✓ [415/2740] Unidade 13475 | MAE: 0.2897
✓ [416/2740] Unidade 13476 | MAE: 0.1554
✓ [417/2740] Unidade 13478 | MAE: 0.1422
✓ [418/2740] Unidade 13479 | MAE: 0.2251
✓ [419/2740] Unidade 13480 | MAE: 0.0896
✓ [420/2740] Unidade 13481 | MAE: 0.2839
✓ [421/2740] Unidade 13482 | MAE: 0.1734
✓ [422/2740] Unidade 13483 | MAE: 0.1692
✓ [423/2740] Unidade 13484 | MAE: 0.2006
✓ [424/2740] Unidade 13485 | MAE: 0.1724
✓ [425/2740] Unidade 13487 | MAE: 0.3770
✓ [426/2740] Unidade 13488 | MAE: 0.1761
✓ [427/2740] Unidade 13489 | MAE: 0.3261
✓ [428/2740] Unidade 13490 | MAE: 0.1853
✓ [429/2740] Unidade 13491 | MAE: 0.1047
✓ [430/2740] Unidade 13492 | MAE: 0.1323
✓ [431/2740] Unidade 13494 | MAE: 0.1616
✓ [432/2740] Unidade 13496 | MAE: 0.2080
✓ [433/2740] Unidade 13497 | MAE: 0.1911
✓ [434/2740] Unidade 13499 | MAE: 0.1433
✓ [435/2740] Unidade 13501 | MAE: 0.3198
✓ [436/2740] Unidade 13503 | MAE: 0.2259
✓ [437/2740] Unidade 13504 | MAE: 0.0930
✓ [438/2740] Unidade 13505 | MAE: 0.0837
✓ [439/2740] Unidade 13506 | MAE: 0.2200
✓ [440/2740] Unidade 13508 | MAE: 0.3699
✓ [441/2740] Unidade 13509 | MAE: 0.0811
✓ [442/2740] Unidade 13511 | MAE: 0.4031
✓ [443/2740] Unidade 13512 | MAE: 0.2665
✓ [444/2740] Unidade 13513 | MAE: 0.4217
✓ [445/2740] Unidade 13514 | MAE: 0.2367
✓ [446/2740] Unidade 13516 | MAE: 0.2036
✓ [447/2740] Unidade 13517 | MAE: 0.0936
✓ [448/2740] Unidade 13519 | MAE: 0.2400
✓ [449/2740] Unidade 13520 | MAE: 0.2661
✓ [450/2740] Unidade 13522 | MAE: 0.1669
✓ [451/2740] Unidade 13524 | MAE: 0.1455
✓ [452/2740] Unidade 13525 | MAE: 0.3594
✓ [453/2740] Unidade 13526 | MAE: 0.1311
✓ [454/2740] Unidade 13527 | MAE: 0.6961
✓ [455/2740] Unidade 13528 | MAE: 0.1242
✓ [456/2740] Unidade 13529 | MAE: 0.1213
✓ [457/2740] Unidade 13530 | MAE: 0.0796
✓ [458/2740] Unidade 13532 | MAE: 0.2444
✓ [459/2740] Unidade 13536 | MAE: 0.2182
✓ [460/2740] Unidade 13537 | MAE: 0.0977
✓ [461/2740] Unidade 13538 | MAE: 0.0601
✓ [462/2740] Unidade 13539 | MAE: 0.1912
✓ [463/2740] Unidade 13540 | MAE: 0.1143
✓ [464/2740] Unidade 13541 | MAE: 0.0617
✓ [465/2740] Unidade 13542 | MAE: 0.2162
✓ [466/2740] Unidade 13544 | MAE: 0.1393
✓ [467/2740] Unidade 13546 | MAE: 0.2042
✓ [468/2740] Unidade 13548 | MAE: 0.1605
✓ [469/2740] Unidade 13550 | MAE: 0.5964
✓ [470/2740] Unidade 13552 | MAE: 0.3948
✓ [471/2740] Unidade 13556 | MAE: 0.1179
✓ [472/2740] Unidade 13557 | MAE: 0.3391
✓ [473/2740] Unidade 13558 | MAE: 0.6387
✓ [474/2740] Unidade 13561 | MAE: 0.1978
✓ [475/2740] Unidade 13563 | MAE: 0.2228
✓ [476/2740] Unidade 13564 | MAE: 0.3743
✓ [477/2740] Unidade 13566 | MAE: 0.2802
✓ [478/2740] Unidade 13567 | MAE: 0.1732
✓ [479/2740] Unidade 13568 | MAE: 0.1265
✓ [480/2740] Unidade 13571 | MAE: 0.3163
✓ [481/2740] Unidade 13572 | MAE: 0.1975
✓ [482/2740] Unidade 13573 | MAE: 0.0826
✓ [483/2740] Unidade 13574 | MAE: 0.1652
✓ [484/2740] Unidade 13575 | MAE: 0.3575
✓ [485/2740] Unidade 13577 | MAE: 0.1224
✓ [486/2740] Unidade 13578 | MAE: 0.3700
✓ [487/2740] Unidade 13579 | MAE: 0.3636
✓ [488/2740] Unidade 13580 | MAE: 0.2160
✓ [489/2740] Unidade 13581 | MAE: 0.1670
✓ [490/2740] Unidade 13582 | MAE: 0.1422

In [ ]:
# 8. Exportação final de resultados - DEC

if todas_previsoes_dec:
    df_todas_previsoes_dec = pd.concat(todas_previsoes_dec, ignore_index=True)
    df_todas_previsoes_dec['data'] = df_todas_previsoes_dec['data'].dt.strftime('%Y-%m-%d')
    df_todas_previsoes_dec.to_csv(
        CAMINHO_PREVISOES_DEC,
        sep=';', decimal=',', index=False
    )
    print(f'✓ CSV final salvo em: {CAMINHO_PREVISOES_DEC}')
    print(f'  Total de linhas     : {len(df_todas_previsoes_dec)}')
    print(f'  Unidades processadas: {df_todas_previsoes_dec["cod_unidade"].nunique()}')
    print()
    print(df_todas_previsoes_dec.head(10))
else:
    print('⚠ Nenhuma previsão DEC gerada para exportar.')

✓ CSV final salvo em: /content/drive/MyDrive/API-6/previsoes_dec_prophet_todas_unidades.csv
  Total de linhas     : 30768
  Unidades processadas: 2564

   cod_unidade indicador       mae        data  previsao  previsao_lower  \
0          964       DEC  0.264269  2026-03-01  0.667080        0.316575
1          964       DEC  0.264269  2026-04-01  0.255178       -0.065189
2          964       DEC  0.264269  2026-05-01  0.335213       -0.014525
3          964       DEC  0.264269  2026-06-01  0.213436       -0.131305
4          964       DEC  0.264269  2026-07-01  0.265024       -0.115456
5          964       DEC  0.264269  2026-08-01  0.224720       -0.103880
6          964       DEC  0.264269  2026-09-01  0.305017       -0.035240
7          964       DEC  0.264269  2026-10-01  0.582870        0.238661
8          964       DEC  0.264269  2026-11-01  0.476119        0.090450
9          964       DEC  0.264269  2026-12-01  0.674364        0.307720

   previsao_upper
0        0.996648
1        0.577935
2        0.686080
3        0.554943
4        0.603357
5        0.575290
6        0.649637
7        0.935410
8        0.805247
9        1.009615

## INÍCIO DE TRATAMENTO PARA SÉRIES TEMPORAIS E TREINAMENTO COM PROPHET - FEC

In [ ]:
# 9. Preparação da série FEC

df_fec = df_indicadores[df_indicadores['SigIndicador'] == 'FEC'].copy()
df_fec = df_fec.dropna(subset=['NumPeriodoIndice'])
df_fec['data'] = pd.to_datetime(
    df_fec['AnoIndice'].astype(int).astype(str) + '-' +
    df_fec['NumPeriodoIndice_key'].astype(int).astype(str).str.zfill(2) + '-01'
)

data_max_fec = '2026-02-01'
ids_validos_fec = df_fec.loc[df_fec['data'] == data_max_fec, 'IdeConjUndConsumidoras'].unique()

fec_por_agente = (
    df_fec[df_fec['IdeConjUndConsumidoras'].isin(ids_validos_fec)]
    .sort_values(['IdeConjUndConsumidoras', 'data'])
)

print(f'Unidades FEC válidas: {len(ids_validos_fec)}')
fec_por_agente.head()

Unidades FEC válidas: 2740

,IdeConjUndConsumidoras,SigIndicador,AnoIndice,NumPeriodoIndice,VlrIndiceEnviado,TipoRegistro,NumPeriodoIndice_key,data
610135,964,FEC,2015,1.0,0.50,Apurado,1,2015-01-01
614515,964,FEC,2015,2.0,1.18,Apurado,2,2015-02-01
621085,964,FEC,2015,3.0,0.84,Apurado,3,2015-03-01
612763,964,FEC,2015,4.0,0.13,Apurado,4,2015-04-01
636196,964,FEC,2015,5.0,0.92,Apurado,5,2015-05-01

In [ ]:
# 10. Treinamento Prophet para todas as unidades - FEC
#
# Reutiliza a mesma função processar_unidade_prophet — apenas passa indicador='FEC'

CAMINHO_PREVISOES_FEC = '/content/drive/MyDrive/API-6/previsoes_fec_prophet_todas_unidades.csv'

todas_unidades_fec  = fec_por_agente['IdeConjUndConsumidoras'].unique()
resultados_fec      = []
todas_previsoes_fec = []

for i, cod in enumerate(todas_unidades_fec, start=1):
    df_unit = fec_por_agente[fec_por_agente['IdeConjUndConsumidoras'] == cod].copy()
    try:
        res = processar_unidade_prophet(cod, df_unit, indicador='FEC')
        if res:
            resultados_fec.append({'cod_unidade': res['cod_unidade'], 'mae': res['mae']})
            todas_previsoes_fec.append(res['previsoes'])
            print(f"✓ [{i}/{len(todas_unidades_fec)}] Unidade {cod} | MAE: {res['mae']:.4f}")
        else:
            print(f"⚠ [{i}/{len(todas_unidades_fec)}] Unidade {cod} | ignorada (dados insuficientes)")
    except Exception as e:
        print(f"✗ [{i}/{len(todas_unidades_fec)}] Unidade {cod} | erro: {e}")
    finally:
        gc.collect()

    # Checkpoint parcial
    if i % CHECKPOINT == 0 and todas_previsoes_fec:
        pd.concat(todas_previsoes_fec, ignore_index=True).assign(
            data=lambda d: d['data'].dt.strftime('%Y-%m-%d')
        ).to_csv(CAMINHO_PREVISOES_FEC, sep=';', decimal=',', index=False)
        print(f"  → Checkpoint salvo ({i} unidades processadas)")

✓ [1/2740] Unidade 964 | MAE: 0.2003
✓ [2/2740] Unidade 2142 | MAE: 0.2284
✓ [3/2740] Unidade 2922 | MAE: 0.1007
✓ [4/2740] Unidade 5273 | MAE: 0.1670
✓ [5/2740] Unidade 12474 | MAE: 0.3429
✓ [6/2740] Unidade 12475 | MAE: 0.5598
✓ [7/2740] Unidade 12476 | MAE: 0.0967
✓ [8/2740] Unidade 12477 | MAE: 0.3403
✓ [9/2740] Unidade 12478 | MAE: 0.4319
✓ [10/2740] Unidade 12479 | MAE: 0.3602
✓ [11/2740] Unidade 12481 | MAE: 0.5462
✓ [12/2740] Unidade 12482 | MAE: 0.2100
✓ [13/2740] Unidade 12483 | MAE: 0.2554
✓ [14/2740] Unidade 12484 | MAE: 0.4827
✓ [15/2740] Unidade 12485 | MAE: 0.2992
✓ [16/2740] Unidade 12486 | MAE: 0.6310
✓ [17/2740] Unidade 12487 | MAE: 0.6128
✓ [18/2740] Unidade 12488 | MAE: 0.5004
✓ [19/2740] Unidade 12489 | MAE: 1.2576
✓ [20/2740] Unidade 12524 | MAE: 0.4100
✓ [21/2740] Unidade 12525 | MAE: 0.5228
✓ [22/2740] Unidade 12532 | MAE: 0.5248
✓ [23/2740] Unidade 12539 | MAE: 0.1759
✓ [24/2740] Unidade 12540 | MAE: 0.2919
✓ [25/2740] Unidade 12541 | MAE: 0.5916
✓ [26/2740] Unidade 12542 | MAE: 0.2576
✓ [27/2740] Unidade 12543 | MAE: 0.6416
✓ [28/2740] Unidade 12546 | MAE: 0.6326
✓ [29/2740] Unidade 12547 | MAE: 0.2128
✓ [30/2740] Unidade 12553 | MAE: 0.3170
✓ [31/2740] Unidade 12559 | MAE: 0.1697
✓ [32/2740] Unidade 12570 | MAE: 0.2407
✓ [33/2740] Unidade 12571 | MAE: 0.7996
✓ [34/2740] Unidade 12574 | MAE: 0.3361
✓ [35/2740] Unidade 12575 | MAE: 0.3737
✓ [36/2740] Unidade 12576 | MAE: 2.3684
✓ [37/2740] Unidade 12582 | MAE: 1.8815
✓ [38/2740] Unidade 12584 | MAE: 1.3644
✓ [39/2740] Unidade 12586 | MAE: 0.2404
✓ [40/2740] Unidade 12589 | MAE: 0.5491
✓ [41/2740] Unidade 12591 | MAE: 1.4157
✓ [42/2740] Unidade 12592 | MAE: 1.0230
✓ [43/2740] Unidade 12593 | MAE: 0.9733
✓ [44/2740] Unidade 12594 | MAE: 1.3882
✓ [45/2740] Unidade 12595 | MAE: 0.9264
✓ [46/2740] Unidade 12598 | MAE: 2.4723
✓ [47/2740] Unidade 12599 | MAE: 1.0943
✓ [48/2740] Unidade 12600 | MAE: 0.4060
✓ [49/2740] Unidade 12634 | MAE: 0.2101
✓ [50/2740] Unidade 12635 | MAE: 0.3798
✓ [51/2740] Unidade 12636 | MAE: 0.2540
✓ [52/2740] Unidade 12638 | MAE: 0.3517
✓ [53/2740] Unidade 12639 | MAE: 0.1030
✓ [54/2740] Unidade 12640 | MAE: 0.2025
✓ [55/2740] Unidade 12644 | MAE: 0.4055
✓ [56/2740] Unidade 12648 | MAE: 0.4816
✓ [57/2740] Unidade 12649 | MAE: 0.3661
✓ [58/2740] Unidade 12652 | MAE: 0.3316
✓ [59/2740] Unidade 12654 | MAE: 0.3492
✓ [60/2740] Unidade 12656 | MAE: 0.6237
✓ [61/2740] Unidade 12657 | MAE: 0.2316
✓ [62/2740] Unidade 12658 | MAE: 0.7692
✓ [63/2740] Unidade 12664 | MAE: 0.8400
✓ [64/2740] Unidade 12668 | MAE: 0.1763
✓ [65/2740] Unidade 12671 | MAE: 0.2757
✓ [66/2740] Unidade 12673 | MAE: 0.4275
✓ [67/2740] Unidade 12674 | MAE: 0.2032
✓ [68/2740] Unidade 12680 | MAE: 0.1573
✓ [69/2740] Unidade 12681 | MAE: 0.0952
✓ [70/2740] Unidade 12683 | MAE: 0.5149
✓ [71/2740] Unidade 12686 | MAE: 0.5249
✓ [72/2740] Unidade 12687 | MAE: 0.3669
✓ [73/2740] Unidade 12688 | MAE: 0.3480
✓ [74/2740] Unidade 12689 | MAE: 0.7242
✓ [75/2740] Unidade 12690 | MAE: 0.4331
✓ [76/2740] Unidade 12691 | MAE: 0.5884
✓ [77/2740] Unidade 12696 | MAE: 0.4703
✓ [78/2740] Unidade 12703 | MAE: 0.4983
✓ [79/2740] Unidade 12706 | MAE: 0.3863
✓ [80/2740] Unidade 12707 | MAE: 0.5165
✓ [81/2740] Unidade 12708 | MAE: 0.5115
✓ [82/2740] Unidade 12709 | MAE: 0.6598
✓ [83/2740] Unidade 12711 | MAE: 0.3203
✓ [84/2740] Unidade 12713 | MAE: 0.3092
✓ [85/2740] Unidade 12715 | MAE: 0.9877
✓ [86/2740] Unidade 12716 | MAE: 0.3776
✓ [87/2740] Unidade 12718 | MAE: 0.1569
✓ [88/2740] Unidade 12720 | MAE: 0.7270
✓ [89/2740] Unidade 12721 | MAE: 0.2127
✓ [90/2740] Unidade 12722 | MAE: 0.1705
✓ [91/2740] Unidade 12723 | MAE: 0.1647
✓ [92/2740] Unidade 12730 | MAE: 0.1883
✓ [93/2740] Unidade 12743 | MAE: 0.2554
✓ [94/2740] Unidade 12785 | MAE: 0.1512
✓ [95/2740] Unidade 12786 | MAE: 0.3026
✓ [96/2740] Unidade 12788 | MAE: 0.3081
✓ [97/2740] Unidade 12791 | MAE: 0.1933
✓ [98/2740] Unidade 12798 | MAE: 0.2043
✓ [99/2740] Unidade 12800 | MAE: 0.2274
✓ [100/2740] Unidade 12803 | MAE: 0.9871
✓ [101/2740] Unidade 12805 | MAE: 0.1968
✓ [102/2740] Unidade 12807 | MAE: 0.2116
✓ [103/2740] Unidade 12819 | MAE: 0.2214
✓ [104/2740] Unidade 12825 | MAE: 0.3262
✓ [105/2740] Unidade 12827 | MAE: 0.2902
✓ [106/2740] Unidade 12829 | MAE: 0.2385
✓ [107/2740] Unidade 12831 | MAE: 1.0327
✓ [108/2740] Unidade 12832 | MAE: 0.2607
✓ [109/2740] Unidade 12834 | MAE: 0.2675
✓ [110/2740] Unidade 12836 | MAE: 0.2564
✓ [111/2740] Unidade 12840 | MAE: 0.3498
✓ [112/2740] Unidade 12847 | MAE: 0.1996
✓ [113/2740] Unidade 12849 | MAE: 0.1813
✓ [114/2740] Unidade 12850 | MAE: 0.3916
✓ [115/2740] Unidade 12852 | MAE: 0.3381
✓ [116/2740] Unidade 12854 | MAE: 0.3663
✓ [117/2740] Unidade 12856 | MAE: 0.2048
✓ [118/2740] Unidade 12860 | MAE: 0.2273
✓ [119/2740] Unidade 12863 | MAE: 0.3101
✓ [120/2740] Unidade 12865 | MAE: 0.1196
✓ [121/2740] Unidade 12867 | MAE: 0.3721
✓ [122/2740] Unidade 12869 | MAE: 0.2058
✓ [123/2740] Unidade 12871 | MAE: 0.4876
✓ [124/2740] Unidade 12873 | MAE: 0.2117
✓ [125/2740] Unidade 12875 | MAE: 0.4205
✓ [126/2740] Unidade 12878 | MAE: 0.1511
✓ [127/2740] Unidade 12879 | MAE: 0.1461
✓ [128/2740] Unidade 12881 | MAE: 0.2685
✓ [129/2740] Unidade 12884 | MAE: 0.2445
✓ [130/2740] Unidade 12886 | MAE: 0.5107
✓ [131/2740] Unidade 12888 | MAE: 0.3414
✓ [132/2740] Unidade 12889 | MAE: 0.5731
✓ [133/2740] Unidade 12891 | MAE: 0.5450
✓ [134/2740] Unidade 12894 | MAE: 0.2340
✓ [135/2740] Unidade 12898 | MAE: 0.2242
✓ [136/2740] Unidade 12901 | MAE: 0.2314
✓ [137/2740] Unidade 12903 | MAE: 0.2819
✓ [138/2740] Unidade 12905 | MAE: 0.3282
✓ [139/2740] Unidade 13015 | MAE: 0.1987
✓ [140/2740] Unidade 13016 | MAE: 0.3794
✓ [141/2740] Unidade 13017 | MAE: 0.2139
✓ [142/2740] Unidade 13019 | MAE: 0.3012
✓ [143/2740] Unidade 13021 | MAE: 0.3090
✓ [144/2740] Unidade 13022 | MAE: 0.4631
✓ [145/2740] Unidade 13024 | MAE: 0.4087
✓ [146/2740] Unidade 13025 | MAE: 0.2638
✓ [147/2740] Unidade 13027 | MAE: 0.2258
✓ [148/2740] Unidade 13028 | MAE: 0.3177
✓ [149/2740] Unidade 13031 | MAE: 0.2106
✓ [150/2740] Unidade 13032 | MAE: 0.2187
✓ [151/2740] Unidade 13033 | MAE: 0.1850
✓ [152/2740] Unidade 13034 | MAE: 0.1622
✓ [153/2740] Unidade 13035 | MAE: 0.1854
✓ [154/2740] Unidade 13037 | MAE: 0.1549
✓ [155/2740] Unidade 13038 | MAE: 0.1517
✓ [156/2740] Unidade 13040 | MAE: 0.3622
✓ [157/2740] Unidade 13041 | MAE: 0.3152
✓ [158/2740] Unidade 13042 | MAE: 0.1050
✓ [159/2740] Unidade 13043 | MAE: 0.3002
✓ [160/2740] Unidade 13044 | MAE: 0.1702
✓ [161/2740] Unidade 13045 | MAE: 0.0939
✓ [162/2740] Unidade 13046 | MAE: 0.2742
✓ [163/2740] Unidade 13047 | MAE: 0.2632
✓ [164/2740] Unidade 13048 | MAE: 0.4003
✓ [165/2740] Unidade 13049 | MAE: 0.2786
✓ [166/2740] Unidade 13050 | MAE: 0.2615
✓ [167/2740] Unidade 13051 | MAE: 0.6724
✓ [168/2740] Unidade 13052 | MAE: 0.1317
✓ [169/2740] Unidade 13053 | MAE: 0.4062
✓ [170/2740] Unidade 13055 | MAE: 0.4732
✓ [171/2740] Unidade 13056 | MAE: 0.1732
✓ [172/2740] Unidade 13057 | MAE: 0.3392
✓ [173/2740] Unidade 13058 | MAE: 0.2842
✓ [174/2740] Unidade 13060 | MAE: 0.3592
✓ [175/2740] Unidade 13061 | MAE: 0.2141
✓ [176/2740] Unidade 13064 | MAE: 0.1451
✓ [177/2740] Unidade 13066 | MAE: 0.3425
✓ [178/2740] Unidade 13067 | MAE: 0.1780
✓ [179/2740] Unidade 13068 | MAE: 0.3027
✓ [180/2740] Unidade 13069 | MAE: 0.2274
✓ [181/2740] Unidade 13070 | MAE: 0.4676
✓ [182/2740] Unidade 13071 | MAE: 0.3179
✓ [183/2740] Unidade 13074 | MAE: 0.1371
✓ [184/2740] Unidade 13075 | MAE: 0.2363
✓ [185/2740] Unidade 13076 | MAE: 0.2403
✓ [186/2740] Unidade 13078 | MAE: 0.3463
✓ [187/2740] Unidade 13079 | MAE: 0.1478
✓ [188/2740] Unidade 13080 | MAE: 0.1791
✓ [189/2740] Unidade 13082 | MAE: 0.1357
✓ [190/2740] Unidade 13084 | MAE: 0.3361
✓ [191/2740] Unidade 13086 | MAE: 0.1407
✓ [192/2740] Unidade 13087 | MAE: 0.3888
✓ [193/2740] Unidade 13088 | MAE: 0.4718
✓ [194/2740] Unidade 13089 | MAE: 0.3330
✓ [195/2740] Unidade 13090 | MAE: 0.4205
✓ [196/2740] Unidade 13091 | MAE: 0.1509
✓ [197/2740] Unidade 13092 | MAE: 0.2763
✓ [198/2740] Unidade 13093 | MAE: 0.2575
✓ [199/2740] Unidade 13094 | MAE: 0.2975
✓ [200/2740] Unidade 13098 | MAE: 0.2436
✓ [201/2740] Unidade 13103 | MAE: 0.4824
✓ [202/2740] Unidade 13104 | MAE: 0.3332
✓ [203/2740] Unidade 13107 | MAE: 0.2313
✓ [204/2740] Unidade 13108 | MAE: 0.3332
✓ [205/2740] Unidade 13109 | MAE: 0.2874
✓ [206/2740] Unidade 13111 | MAE: 0.4816
✓ [207/2740] Unidade 13112 | MAE: 0.4189
✓ [208/2740] Unidade 13114 | MAE: 0.1906
✓ [209/2740] Unidade 13115 | MAE: 0.3774
✓ [210/2740] Unidade 13116 | MAE: 0.2965
✓ [211/2740] Unidade 13118 | MAE: 0.3937
✓ [212/2740] Unidade 13119 | MAE: 0.3909
✓ [213/2740] Unidade 13122 | MAE: 0.4835
✓ [214/2740] Unidade 13123 | MAE: 0.4089
✓ [215/2740] Unidade 13124 | MAE: 0.2663
✓ [216/2740] Unidade 13129 | MAE: 0.1509
✓ [217/2740] Unidade 13133 | MAE: 0.2764
✓ [218/2740] Unidade 13136 | MAE: 0.2871
✓ [219/2740] Unidade 13137 | MAE: 0.3377
✓ [220/2740] Unidade 13138 | MAE: 0.3114
✓ [221/2740] Unidade 13155 | MAE: 0.1699
✓ [222/2740] Unidade 13166 | MAE: 0.0730
✓ [223/2740] Unidade 13178 | MAE: 0.0906
✓ [224/2740] Unidade 13183 | MAE: 0.1626
✓ [225/2740] Unidade 13185 | MAE: 0.1950
✓ [226/2740] Unidade 13186 | MAE: 0.1914
✓ [227/2740] Unidade 13187 | MAE: 0.3004
✓ [228/2740] Unidade 13188 | MAE: 0.1966
✓ [229/2740] Unidade 13189 | MAE: 0.1246
✓ [230/2740] Unidade 13191 | MAE: 0.0890
✓ [231/2740] Unidade 13192 | MAE: 0.1374
✓ [232/2740] Unidade 13193 | MAE: 0.1343
✓ [233/2740] Unidade 13194 | MAE: 0.3608
✓ [234/2740] Unidade 13201 | MAE: 0.3637
✓ [235/2740] Unidade 13202 | MAE: 0.2412
✓ [236/2740] Unidade 13204 | MAE: 0.2041
✓ [237/2740] Unidade 13205 | MAE: 0.1665
✓ [238/2740] Unidade 13207 | MAE: 0.1448
✓ [239/2740] Unidade 13208 | MAE: 0.1037
✓ [240/2740] Unidade 13209 | MAE: 0.1764
✓ [241/2740] Unidade 13214 | MAE: 0.1516
✓ [242/2740] Unidade 13216 | MAE: 0.2833
✓ [243/2740] Unidade 13218 | MAE: 0.2257
✓ [244/2740] Unidade 13219 | MAE: 0.1061
✓ [245/2740] Unidade 13220 | MAE: 0.0756
✓ [246/2740] Unidade 13226 | MAE: 0.1213
✓ [247/2740] Unidade 13230 | MAE: 0.1536
✓ [248/2740] Unidade 13234 | MAE: 0.3908
✓ [249/2740] Unidade 13235 | MAE: 0.2585
✓ [250/2740] Unidade 13236 | MAE: 0.2032
✓ [251/2740] Unidade 13238 | MAE: 0.5200
✓ [252/2740] Unidade 13239 | MAE: 0.1165
✓ [253/2740] Unidade 13240 | MAE: 0.3833
✓ [254/2740] Unidade 13242 | MAE: 0.3083
✓ [255/2740] Unidade 13244 | MAE: 0.5124
✓ [256/2740] Unidade 13245 | MAE: 0.4178
✓ [257/2740] Unidade 13246 | MAE: 0.3639
✓ [258/2740] Unidade 13247 | MAE: 0.4750
✓ [259/2740] Unidade 13248 | MAE: 0.2437
✓ [260/2740] Unidade 13249 | MAE: 0.1568
✓ [261/2740] Unidade 13250 | MAE: 0.5638
✓ [262/2740] Unidade 13251 | MAE: 0.4563
✓ [263/2740] Unidade 13252 | MAE: 0.2901
✓ [264/2740] Unidade 13253 | MAE: 0.1677
✓ [265/2740] Unidade 13254 | MAE: 0.2528
✓ [266/2740] Unidade 13255 | MAE: 0.1823
✓ [267/2740] Unidade 13256 | MAE: 0.2517
✓ [268/2740] Unidade 13257 | MAE: 0.4421
✓ [269/2740] Unidade 13258 | MAE: 0.2825
✓ [270/2740] Unidade 13260 | MAE: 0.3170
✓ [271/2740] Unidade 13261 | MAE: 0.2430
✓ [272/2740] Unidade 13263 | MAE: 0.2627
✓ [273/2740] Unidade 13264 | MAE: 0.2810
✓ [274/2740] Unidade 13265 | MAE: 0.2122
✓ [275/2740] Unidade 13267 | MAE: 0.4413
✓ [276/2740] Unidade 13270 | MAE: 0.1848
✓ [277/2740] Unidade 13272 | MAE: 0.2382
✓ [278/2740] Unidade 13273 | MAE: 0.1489
✓ [279/2740] Unidade 13274 | MAE: 0.1105
✓ [280/2740] Unidade 13275 | MAE: 0.3710
✓ [281/2740] Unidade 13276 | MAE: 0.1513
✓ [282/2740] Unidade 13279 | MAE: 0.4219
✓ [283/2740] Unidade 13280 | MAE: 0.2884
✓ [284/2740] Unidade 13281 | MAE: 0.0914
✓ [285/2740] Unidade 13282 | MAE: 0.1906
✓ [286/2740] Unidade 13283 | MAE: 0.2935
✓ [287/2740] Unidade 13284 | MAE: 0.2762
✓ [288/2740] Unidade 13285 | MAE: 0.4494
✓ [289/2740] Unidade 13286 | MAE: 0.6233
✓ [290/2740] Unidade 13288 | MAE: 0.4983
✓ [291/2740] Unidade 13289 | MAE: 0.2250
✓ [292/2740] Unidade 13290 | MAE: 0.1511
✓ [293/2740] Unidade 13291 | MAE: 0.2421
✓ [294/2740] Unidade 13292 | MAE: 0.1391
✓ [295/2740] Unidade 13293 | MAE: 0.1205
✓ [296/2740] Unidade 13295 | MAE: 0.1173
✓ [297/2740] Unidade 13296 | MAE: 0.1574
✓ [298/2740] Unidade 13297 | MAE: 0.1417
✓ [299/2740] Unidade 13298 | MAE: 0.3008
✓ [300/2740] Unidade 13299 | MAE: 0.2079
✓ [301/2740] Unidade 13300 | MAE: 0.1267
✓ [302/2740] Unidade 13302 | MAE: 0.2958
✓ [303/2740] Unidade 13304 | MAE: 0.2934
✓ [304/2740] Unidade 13305 | MAE: 0.2643
✓ [305/2740] Unidade 13307 | MAE: 0.5347
✓ [306/2740] Unidade 13308 | MAE: 0.2102
✓ [307/2740] Unidade 13312 | MAE: 0.3392
✓ [308/2740] Unidade 13314 | MAE: 0.4870
✓ [309/2740] Unidade 13315 | MAE: 0.3841
✓ [310/2740] Unidade 13317 | MAE: 0.2793
✓ [311/2740] Unidade 13318 | MAE: 0.2180
✓ [312/2740] Unidade 13319 | MAE: 0.1752
✓ [313/2740] Unidade 13320 | MAE: 0.1695
✓ [314/2740] Unidade 13321 | MAE: 0.3848
✓ [315/2740] Unidade 13322 | MAE: 0.2211
✓ [316/2740] Unidade 13325 | MAE: 0.2626
✓ [317/2740] Unidade 13327 | MAE: 0.5101
✓ [318/2740] Unidade 13328 | MAE: 0.2968
✓ [319/2740] Unidade 13329 | MAE: 0.2018
✓ [320/2740] Unidade 13330 | MAE: 0.4016
✓ [321/2740] Unidade 13331 | MAE: 0.4014
✓ [322/2740] Unidade 13332 | MAE: 0.2411
✓ [323/2740] Unidade 13334 | MAE: 0.1227
✓ [324/2740] Unidade 13336 | MAE: 0.2038
✓ [325/2740] Unidade 13339 | MAE: 0.1629
✓ [326/2740] Unidade 13340 | MAE: 0.3555
✓ [327/2740] Unidade 13342 | MAE: 0.0789
✓ [328/2740] Unidade 13343 | MAE: 0.3772
✓ [329/2740] Unidade 13344 | MAE: 0.3357
✓ [330/2740] Unidade 13345 | MAE: 0.1749
✓ [331/2740] Unidade 13346 | MAE: 0.2971
✓ [332/2740] Unidade 13347 | MAE: 0.3681
✓ [333/2740] Unidade 13348 | MAE: 0.1832
✓ [334/2740] Unidade 13351 | MAE: 0.1120
✓ [335/2740] Unidade 13352 | MAE: 0.2160
✓ [336/2740] Unidade 13353 | MAE: 0.1595
✓ [337/2740] Unidade 13355 | MAE: 0.6126
✓ [338/2740] Unidade 13356 | MAE: 0.2271
✓ [339/2740] Unidade 13357 | MAE: 0.2604
✓ [340/2740] Unidade 13359 | MAE: 0.1527
✓ [341/2740] Unidade 13360 | MAE: 0.1375
✓ [342/2740] Unidade 13363 | MAE: 0.1651
✓ [343/2740] Unidade 13364 | MAE: 0.3560
✓ [344/2740] Unidade 13365 | MAE: 0.1041
✓ [345/2740] Unidade 13367 | MAE: 0.1567
✓ [346/2740] Unidade 13369 | MAE: 0.2374
✓ [347/2740] Unidade 13370 | MAE: 0.2470
✓ [348/2740] Unidade 13372 | MAE: 0.2923
✓ [349/2740] Unidade 13374 | MAE: 0.1774
✓ [350/2740] Unidade 13375 | MAE: 0.4159
✓ [351/2740] Unidade 13376 | MAE: 0.1473
✓ [352/2740] Unidade 13381 | MAE: 0.0917
✓ [353/2740] Unidade 13382 | MAE: 0.1848
✓ [354/2740] Unidade 13384 | MAE: 0.2771
✓ [355/2740] Unidade 13385 | MAE: 0.2103
✓ [356/2740] Unidade 13387 | MAE: 0.2927
✓ [357/2740] Unidade 13388 | MAE: 0.3748
✓ [358/2740] Unidade 13389 | MAE: 0.3553
✓ [359/2740] Unidade 13390 | MAE: 0.4531
✓ [360/2740] Unidade 13391 | MAE: 0.3728
✓ [361/2740] Unidade 13392 | MAE: 0.1982
✓ [362/2740] Unidade 13394 | MAE: 0.2697
✓ [363/2740] Unidade 13395 | MAE: 0.1340
✓ [364/2740] Unidade 13396 | MAE: 0.5365
✓ [365/2740] Unidade 13397 | MAE: 0.1215
✓ [366/2740] Unidade 13398 | MAE: 0.4958
✓ [367/2740] Unidade 13399 | MAE: 0.1082
✓ [368/2740] Unidade 13401 | MAE: 0.2038
✓ [369/2740] Unidade 13402 | MAE: 0.3687
✓ [370/2740] Unidade 13408 | MAE: 0.2974
✓ [371/2740] Unidade 13412 | MAE: 0.7366
✓ [372/2740] Unidade 13413 | MAE: 0.3797
✓ [373/2740] Unidade 13414 | MAE: 0.2449
✓ [374/2740] Unidade 13416 | MAE: 0.2621
✓ [375/2740] Unidade 13417 | MAE: 0.2430
✓ [376/2740] Unidade 13420 | MAE: 0.1650
✓ [377/2740] Unidade 13421 | MAE: 0.1645
✓ [378/2740] Unidade 13423 | MAE: 0.3193
✓ [379/2740] Unidade 13424 | MAE: 0.2208
✓ [380/2740] Unidade 13425 | MAE: 0.4552
✓ [381/2740] Unidade 13426 | MAE: 0.3242
✓ [382/2740] Unidade 13430 | MAE: 0.5764
✓ [383/2740] Unidade 13431 | MAE: 0.3315
✓ [384/2740] Unidade 13432 | MAE: 0.2090
✓ [385/2740] Unidade 13434 | MAE: 0.4727
✓ [386/2740] Unidade 13435 | MAE: 0.1833
✓ [387/2740] Unidade 13438 | MAE: 0.3334
✓ [388/2740] Unidade 13439 | MAE: 0.1147
✓ [389/2740] Unidade 13441 | MAE: 0.2890
✓ [390/2740] Unidade 13443 | MAE: 0.2873
✓ [391/2740] Unidade 13447 | MAE: 0.4127
✓ [392/2740] Unidade 13448 | MAE: 0.3077
✓ [393/2740] Unidade 13449 | MAE: 0.1791
✓ [394/2740] Unidade 13450 | MAE: 0.1719
✓ [395/2740] Unidade 13451 | MAE: 0.1809
✓ [396/2740] Unidade 13452 | MAE: 0.0915
✓ [397/2740] Unidade 13453 | MAE: 0.1977
✓ [398/2740] Unidade 13454 | MAE: 0.1665
✓ [399/2740] Unidade 13455 | MAE: 0.2080
✓ [400/2740] Unidade 13456 | MAE: 0.0767
✓ [401/2740] Unidade 13457 | MAE: 0.1277
✓ [402/2740] Unidade 13458 | MAE: 0.1248
✓ [403/2740] Unidade 13460 | MAE: 0.1469
✓ [404/2740] Unidade 13463 | MAE: 0.2247
✓ [405/2740] Unidade 13465 | MAE: 0.0935
✓ [406/2740] Unidade 13466 | MAE: 0.1223
✓ [407/2740] Unidade 13467 | MAE: 0.1666
✓ [408/2740] Unidade 13468 | MAE: 0.1978
✓ [409/2740] Unidade 13469 | MAE: 0.1049
✓ [410/2740] Unidade 13470 | MAE: 0.1672
✓ [411/2740] Unidade 13471 | MAE: 0.1648
✓ [412/2740] Unidade 13472 | MAE: 0.2187
✓ [413/2740] Unidade 13473 | MAE: 0.1421
✓ [414/2740] Unidade 13474 | MAE: 0.1473
✓ [415/2740] Unidade 13475 | MAE: 0.1545
✓ [416/2740] Unidade 13476 | MAE: 0.1507
✓ [417/2740] Unidade 13478 | MAE: 0.1194
✓ [418/2740] Unidade 13479 | MAE: 0.1389
✓ [419/2740] Unidade 13480 | MAE: 0.1790
✓ [420/2740] Unidade 13481 | MAE: 0.2995
✓ [421/2740] Unidade 13482 | MAE: 0.2005
✓ [422/2740] Unidade 13483 | MAE: 0.1028
✓ [423/2740] Unidade 13484 | MAE: 0.1172
✓ [424/2740] Unidade 13485 | MAE: 0.0905
✓ [425/2740] Unidade 13487 | MAE: 0.1518
✓ [426/2740] Unidade 13488 | MAE: 0.1231
✓ [427/2740] Unidade 13489 | MAE: 0.2533
✓ [428/2740] Unidade 13490 | MAE: 0.1683
✓ [429/2740] Unidade 13491 | MAE: 0.1234
✓ [430/2740] Unidade 13492 | MAE: 0.1076
✓ [431/2740] Unidade 13494 | MAE: 0.0952
✓ [432/2740] Unidade 13496 | MAE: 0.1130
✓ [433/2740] Unidade 13497 | MAE: 0.1371
✓ [434/2740] Unidade 13499 | MAE: 0.0813
✓ [435/2740] Unidade 13501 | MAE: 0.2224
✓ [436/2740] Unidade 13503 | MAE: 0.1235
✓ [437/2740] Unidade 13504 | MAE: 0.0779
✓ [438/2740] Unidade 13505 | MAE: 0.0889
✓ [439/2740] Unidade 13506 | MAE: 0.2599
✓ [440/2740] Unidade 13508 | MAE: 0.1861
✓ [441/2740] Unidade 13509 | MAE: 0.0864
✓ [442/2740] Unidade 13511 | MAE: 0.1984
✓ [443/2740] Unidade 13512 | MAE: 0.1230
✓ [444/2740] Unidade 13513 | MAE: 0.3705
✓ [445/2740] Unidade 13514 | MAE: 0.1296
✓ [446/2740] Unidade 13516 | MAE: 0.1766
✓ [447/2740] Unidade 13517 | MAE: 0.0908
✓ [448/2740] Unidade 13519 | MAE: 0.1416
✓ [449/2740] Unidade 13520 | MAE: 0.1766
✓ [450/2740] Unidade 13522 | MAE: 0.1487
✓ [451/2740] Unidade 13524 | MAE: 0.1266
✓ [452/2740] Unidade 13525 | MAE: 0.1608
✓ [453/2740] Unidade 13526 | MAE: 0.1315
✓ [454/2740] Unidade 13527 | MAE: 0.2260
✓ [455/2740] Unidade 13528 | MAE: 0.0958
✓ [456/2740] Unidade 13529 | MAE: 0.0839
✓ [457/2740] Unidade 13530 | MAE: 0.0500
✓ [458/2740] Unidade 13532 | MAE: 0.1346
✓ [459/2740] Unidade 13536 | MAE: 0.1126
✓ [460/2740] Unidade 13537 | MAE: 0.0840
✓ [461/2740] Unidade 13538 | MAE: 0.0631
✓ [462/2740] Unidade 13539 | MAE: 0.2142
✓ [463/2740] Unidade 13540 | MAE: 0.0807
✓ [464/2740] Unidade 13541 | MAE: 0.0620
✓ [465/2740] Unidade 13542 | MAE: 0.1724
✓ [466/2740] Unidade 13544 | MAE: 0.1302
✓ [467/2740] Unidade 13546 | MAE: 0.1110
✓ [468/2740] Unidade 13548 | MAE: 0.1693
✓ [469/2740] Unidade 13550 | MAE: 0.2784
✓ [470/2740] Unidade 13552 | MAE: 0.2680
✓ [471/2740] Unidade 13556 | MAE: 0.1421
✓ [472/2740] Unidade 13557 | MAE: 0.2393
✓ [473/2740] Unidade 13558 | MAE: 0.2031
✓ [474/2740] Unidade 13561 | MAE: 0.1243
✓ [475/2740] Unidade 13563 | MAE: 0.1455
✓ [476/2740] Unidade 13564 | MAE: 0.1426
✓ [477/2740] Unidade 13566 | MAE: 0.1316
✓ [478/2740] Unidade 13567 | MAE: 0.1639
✓ [479/2740] Unidade 13568 | MAE: 0.1224
✓ [480/2740] Unidade 13571 | MAE: 0.2393
✓ [481/2740] Unidade 13572 | MAE: 0.1540
✓ [482/2740] Unidade 13573 | MAE: 0.0666
✓ [483/2740] Unidade 13574 | MAE: 0.1752
✓ [484/2740] Unidade 13575 | MAE: 0.1399
✓ [485/2740] Unidade 13577 | MAE: 0.0984
✓ [486/2740] Unidade 13578 | MAE: 0.2012
✓ [487/2740] Unidade 13579 | MAE: 0.2004
✓ [488/2740] Unidade 13580 | MAE: 0.1596
✓ [489/2740] Unidade 13581 | MAE: 0.1448
✓ [490/2740] Unidade 13582 | MAE: 0.1055

In [ ]:
# 11. Exportação final de resultados - FEC

if todas_previsoes_fec:
    df_todas_previsoes_fec = pd.concat(todas_previsoes_fec, ignore_index=True)
    df_todas_previsoes_fec['data'] = df_todas_previsoes_fec['data'].dt.strftime('%Y-%m-%d')
    df_todas_previsoes_fec.to_csv(
        CAMINHO_PREVISOES_FEC,
        sep=';', decimal=',', index=False
    )
    print(f'✓ CSV final salvo em: {CAMINHO_PREVISOES_FEC}')
    print(f'  Total de linhas     : {len(df_todas_previsoes_fec)}')
    print(f'  Unidades processadas: {df_todas_previsoes_fec["cod_unidade"].nunique()}')
    print()
    print(df_todas_previsoes_fec.head(10))
else:
    print('⚠ Nenhuma previsão FEC gerada para exportar.')

✓ CSV final salvo em: /content/drive/MyDrive/API-6/previsoes_fec_prophet_todas_unidades.csv
  Total de linhas     : 30768
  Unidades processadas: 2564

   cod_unidade indicador       mae        data  previsao  previsao_lower  \
0          964       FEC  0.200297  2026-03-01  0.333250       -0.012570
1          964       FEC  0.200297  2026-04-01  0.045582       -0.292654
2          964       FEC  0.200297  2026-05-01  0.112273       -0.214639
3          964       FEC  0.200297  2026-06-01 -0.040236       -0.400249
4          964       FEC  0.200297  2026-07-01  0.046968       -0.281905
5          964       FEC  0.200297  2026-08-01  0.009624       -0.332894
6          964       FEC  0.200297  2026-09-01  0.095569       -0.244508
7          964       FEC  0.200297  2026-10-01  0.230683       -0.088792
8          964       FEC  0.200297  2026-11-01  0.150394       -0.195051
9          964       FEC  0.200297  2026-12-01  0.411753        0.066656

   previsao_upper
0        0.654980
1        0.382449
2        0.447089
3        0.286549
4        0.416997
5        0.332571
6        0.454647
7        0.544990
8        0.486127
9        0.753291